[General]
network = src.RaftNetwork
# sim-time-limit = 1000s

# Node failure configuration
*.node[0].crashTime = exponential(1.25s)
*.node[1].crashTime = exponential(1.25s)
*.node[2].crashTime = exponential(1.25s)
*.node[3].crashTime = exponential(1.25s)
*.node[4].crashTime = exponential(1.25s)
*.node[5].crashTime = exponential(1.25s)
*.node[6].crashTime = exponential(1.25s)
*.node[7].crashTime = exponential(1.25s)
*.node[8].crashTime = exponential(1.25s)
*.node[9].crashTime = exponential(1.25s)
*.node[10].crashTime = exponential(1.25s)
*.node[11].crashTime = exponential(1.25s)
*.node[12].crashTime = exponential(1.25s)
*.node[13].crashTime = exponential(1.25s)
*.node[14].crashTime = exponential(1.25s)
# Optional (for terminal mode)
cmdenv-express-mode = false
**.allowunconnected = true

# cmdenv-log-level = info
**.cmdenv-log-level = debug
